- client/dist/index.html
- package-lock.json
- package.json
-changed express version to 4.17.1
-initialized index.html
> intialize index.html and changed express version

- .gitignore
git ignore now blocks everything in client/dist except for index.html and styles.css
> fix: updated git ignore 

- client/src/components/App.jsx
- client/src/components/Card.jsx
-added axios get request for reviews/meta for each card in Related Products and Outfit
-added mock ratings -> star converter
-cleaned up small syntax sugar in App.jsx
> fetched metadata from reviews in Card for star rating

- client/dist/styles.css
- client/src/components/Overview.jsx
- client/src/components/overview/Gallery.jsx
- client/src/components/overview/ProductInfo.jsx
- client/src/components/overview/Thumbnail.jsx
- package-lock.json
- package.json
- installed an icon library
- gallery is displaying images tied to a specific style
- thumbnails preview the upcoming images and indicate which image is currently selected
- ability to make the gallery fullscreen
- arrows that let you navigate between images
- product info rough layout is included
> feat: logic for gallery component

- client/dist/styles.css
- client/src/components/App.jsx
- client/src/components/related_and_outfit/Card.jsx
- client/src/components/related_and_outfit/Carousel.jsx
- client/src/components/related_and_outfit/Outfit.jsx
-added the api call for grabbing each cards' img
-added a button onto each card
-more small changes to the css
-small syntax sugar for a few files
> added the image and button logic for the product and outfit cards

- client/src/components/QA/Answer.jsx
- client/src/components/QA/AnswersList.jsx
- client/src/components/QA/Question.jsx
- client/src/components/QA/index.jsx
- client/src/components/QA/qanda.module.css
Added a component `Answer` with styles imported from a css module. This component renders the answer body, date, answerer name, and helpfulness rating. Stubbed out links to mark an answer as helpful and report an answer.
> Answer styling

- README.md
- client/dist/styles.css
- client/src/components/global.module.css
- added global.module.css
- updated read me with our agreed upon css guidelines
> feat: following new css guidelines

- client/src/components/benRatingsAndReviews/ratings/Ratings.jsx
- client/src/components/benRatingsAndReviews/reviews/ReviewTile.jsx
- client/src/components/benRatingsAndReviews/reviews/addReview/AddReview.jsx
- client/src/components/benRatingsAndReviews/reviews/addReview/CharacteristicInput.jsx
- client/src/components/shared/QuarterStarRating.jsx
- client/src/components/shared/shared.module.css
Refactor for @iWitho QuarterStarReview component.  This would add a few new flags so @drew-dingle and I can repurpose it in the add review modal (but should still work as is in other modules).
**New flags include:** 
1.  **isReview** (automatically set to false) - this flag makes it so the component is hoverable and clickable. Basically it will act like a series of buttons to return a user's selected star rating. 
2. **getRating** - a function passed from the parent to bubble up the star review. Gets ignored if it's not passed in.
3. **size** - set to 16 by default (refactored this a bit so we could customize the star size). 
Everything else should include the implementation of said component in my add reviews modal
> Add review star refactor

- client/src/components/QA/Answer.jsx
- client/src/components/QA/AnswerForm.jsx
- client/src/components/QA/AnswersList.jsx
- client/src/components/QA/Question.jsx
- client/src/components/QA/QuestionForm.jsx
- client/src/components/QA/QuestionsList.jsx
- client/src/components/QA/index.jsx
- client/src/components/QA/qanda.module.css
- client/src/components/shared/PhotoForm.jsx
- fetches "all" the answers and filters through "all" the questions (used count = 999)
- scrollable containers for questions list and answers list
- styling for button/resolving linter issues regarding having click events for <a> tags
- all linter errors have been resolved
- using same productId as the rest of the team!
Note: I merged in the global css stuff from the other PR but haven't refactored my module to fully use those yet.
> QandA rendering fixes, more linter fixes, styling

- client/src/components/App.jsx
- client/src/components/benRatingsAndReviews/BenRatingsAndReviews.jsx
- client/src/components/benRatingsAndReviews/ratings/ProductBreakdown.jsx
- client/src/components/benRatingsAndReviews/ratings/Ratings.jsx
- client/src/components/benRatingsAndReviews/ratings/StarRatingBreakdown.jsx
- client/src/components/benRatingsAndReviews/reviews.module.css
- client/src/components/benRatingsAndReviews/reviews/ReviewTile.jsx
- client/src/components/benRatingsAndReviews/reviews/ReviewsList.jsx
- client/src/components/benRatingsAndReviews/reviews/TruncatedText.jsx
- client/src/components/benRatingsAndReviews/reviews/addReview/AddReview.jsx
- client/src/components/benRatingsAndReviews/reviews/addReview/CharacteristicInput.jsx
Updating reviews to incorporate @eddie-nv stylesheets (for the most part -- still a few things left on my todo list)
> Applying global styles to reviews

- client/src/components/QA/Answer.jsx
- client/src/components/QA/AnswerForm.jsx
- client/src/components/QA/AnswersList.jsx
- client/src/components/QA/Question.jsx
- client/src/components/QA/QuestionForm.jsx
- client/src/components/QA/QuestionsList.jsx
- client/src/components/QA/Search.jsx
- client/src/components/QA/index.jsx
- client/src/components/QA/qanda.module.css
- client/src/components/global.module.css
- client/src/components/shared/PhotoForm.jsx
- client/src/components/shared/Thumbnail.jsx
- client/src/components/shared/shared.module.css
- refactored module to use product instead of currentProductId
- used some more shared styles/components in PhotoForm
- fixed index lint error in PhotoForm (use key={crypto.randomUUID()})
- applying global styles to my module based on the Figma
> Styling QA and PhotoForm with global styles

- client/src/components/overview/Overview.jsx
- client/src/components/overview/components/Footer.jsx
- client/src/components/overview/components/Info.jsx
- client/src/components/overview/styles/footer.module.css
- client/src/components/overview/styles/gallery.module.css
changes I made
- added social app buttons to footer
- star ratings only appear if product has ratings
> feat: adding social app buttons 

- client/src/components/benRatingsAndReviews/BenRatingsAndReviews.jsx
- client/src/components/benRatingsAndReviews/ratings/StarRatingBreakdown.jsx
- client/src/components/benRatingsAndReviews/reviews.module.css
- client/src/components/benRatingsAndReviews/reviews/ReviewTile.jsx
- client/src/components/benRatingsAndReviews/reviews/ReviewsFilters.jsx
- client/src/components/benRatingsAndReviews/reviews/ReviewsList.jsx
- client/src/components/benRatingsAndReviews/reviews/Sort.js
- client/src/components/benRatingsAndReviews/reviews/addReview/AddReview.jsx
Modifying some of the sorting that I'm doing on the front end, updating small css issues, and a photo viewing bug
> Minor fixes to sort

- client/src/components/benRatingsAndReviews/reviews.module.css
- client/src/components/benRatingsAndReviews/reviews/ReviewTile.jsx
- client/src/components/benRatingsAndReviews/reviews/ReviewsList.jsx
adding Ruby's localstorage solution to 'helpfulness' update and removing any instances of crypto for IDs
> UUID fix and localstorage

- client/src/components/benRatingsAndReviews/services/ReviewsServices.js
removes localhost ref in ReviewsServices
> removing my localhost ref

- client/src/components/ratingsAndReviews/ratingsAndReviews.module.css
removes svg line causing load errors.
> commented out line causing loading errors

- client/dist/styles.css
- client/src/components/related_and_outfit/Card.jsx
- client/src/components/related_and_outfit/relatedOutfit.module.css
- client/src/index.jsx
-changed the color of the arrows on the carousel to be the global variable colors for dark mode
-changed original product
-changed background of action button to always be transparent
> Relatedoutfit opt 2

- client/src/components/benRatingsAndReviews/reviews/Sort.js
hopefully this makes my sorting a little more consistent...
> updating sort so there is a tie breaker if dates are the same

- client/dist/styles.css
-changed color-text to color-dark inside of the carousel arrows
> css name change

- server/index.js
fixed type and sort order comparison on relevant sorting fpr Ratings & Reviews.
> updates the relevant sort option to fix a typo and corrected the initial
